### PR TITLE
fix: move catchall down

### PR DESCRIPTION
**Pull request by TobiTenno**
### What did you fix? (provide a description or issue closes statement)
addresses...
image

---

### Reproduction steps
1. moved catchall back to the bottom
2. added tests to enforce some melee. i don't have a good way of forcing all of them, cause that'd take a lot of pre-enumeration.

### Considerations
- Does this contain a new dependency? **[No]**
- Does this introduce opinionated data formatting or manual data entry? **[No]**
- Does this pr include the updated data files in a separate commit that can be reverted for a clean code-only pr? **[Yes]**
- Have I run the linter through `npm run lint`? **[Yes]**
- Is is a bug fix, feature request, or enhancement? **[Bug Fix]**

### CODE REVIEW

**Comment by AyAyEm** [comment]
Maybe i can work with the typings to enforce type and category, like having more interfaces for specific type category keys. That would prevent this kind of issue and some others.

**Comment by AyAyEm** [comment]
Also i just noticed we need to modify the build workflow and force the build when it's not a cronjob, because like with this modification it won't re-build because the upstream data didn't change.

**Review by AyAyEm — APPROVED** [review]
If you wish to also include the changes to CI in this PR, i ask to request the review again.

**Comment by TobiTenno** [comment]
> Maybe i can work with the typings to enforce type and category, like having more interfaces for specific type category keys. That would prevent this kind of issue and some others.

Agreed, but weapons are dicey cause it'd require splitting attacks, I think.

**Pull request merged**
