### PR TITLE
fix: images no longer need resizing

### PR DESCRIPTION
**Pull request by DaPigGuy**
### What did you fix? (provide a description or issue closes statement)
Fixed stretched images as a result of Update 31.1.0 which updated all in-game images to be squares.

---

### Evidence/screenshot/link to line
[Barrel image as of Update 31.1.0](https://github.com/WFCD/warframe-items/blob/master/data/img/barrel.png)
[Barrel image prior to Update 31.1.0](https://github.com/WFCD/warframe-items/blob/2d3c2c56cbeb3c488343b9b66f839d6c52a5f072/data/img/barrel.png)

### Considerations
- Does this contain a new dependency? **No**
- Does this introduce opinionated data formatting or manual data entry? **No**
- Does this pr include the updated data files in a separate commit that can be reverted for a clean code-only pr? **N/A**
- Have I run the linter through `npm run lint`? **Yes**
- Is is a bug fix, feature request, or enhancement? **Bug Fix**

### CODE REVIEW

**Comment by TobiTenno** [comment]
given that it's an overhaul of the images, could you put the overhaul of the images in a separate commit so we don't have that as such a long-running job after this merges? Thanks for your contribution on this, it's much appreciated.

**Comment by DaPigGuy** [comment]
The build has already been running in the background :)

Will push when completed

**Comment by TobiTenno** [comment]
awesome! i'll approve it once that's in so CI can take it the rest of the way.

**Comment by TobiTenno** [comment]
Looking at the image size increase, I'm a little concerned now... I'm stuff now in the morning or in a few days, because an 117% increase per file is a lot...

**Review by TobiTenno — APPROVED** [review]

**Pull request merged**
