### PR TITLE
Check Items against Existing Components

### LINKED ISSUE #52: Image stored name & name in item data mismatch
From what a user and I are seeing, items such as the lato are being stored as `pistol.png`, which would correspond to it's unique name, but the `imageName` field on it is storing `lalto.png`, which doesn't exist.

Actual: 
https://cdn.warframestat.us/img/pistol.png

Expected:
https://cdn.warframestat.us/img/lato.png

### LINKED ISSUE #63: Missing mod images
Hey there,

my program in running through issues when trying to pull the images of the newer mods released. Here is a list of mods with missing images, even though they are defined in the data:

- Ammo Chain
- Desiccation'S Curse
- Molecular Fission
- Quick Reload
- Spectrosiphon
- Venari Bodyguard
- Zaw Riven Mod

### PR DESCRIPTION
**Pull request by TobiTenno**
Fixes image names being mismatched (for the most part) between component and non-component variants. Since we are usually prioritizing the component-named versions, those are what are being used in case of an overlap.

closes #63 
closes #52

### CODE REVIEW

**Comment by TobiTenno** [comment]
@Kaptard this work for you?

**Comment by Kaptard** [comment]
Not sure why the CI has issues pulling this PR. I also won't be able to fully test this until Feb. 22. The bot is running on my rpi at home and I'm still abroad.

If you're confident this works, then feel free to merge this. Looking at the code I don't see any reason why it wouldn't work.

**Comment by TobiTenno** [comment]
oh, it's just the pr part, because i haven't marked it as ready for review, @Kaptard

**Comment by TobiTenno** [comment]
For the hosting provider stuff, genesis has somehow never had issues pinging content and store and such, so it mostly depends on which we can find that works.

**Comment by Hellsing** [comment]
Any updates on this?

**Comment by TobiTenno** [comment]
@Hellsing I'm waiting to hear from kaptard. It works fine for me, but I wanna make sure it meets what he'd expect.

**Comment by Kaptard** [comment]
@TobiTenno Feel free to merge this if you can verify it works as intended, I'm gonna trust you on this.
Got a libpng issue on Debian that I can't get around, so I'd rather not halt progress of this PR any further.

**Pull request merged**
