### PR TITLE
fix: added Augment type

### LINKED ISSUE #107: Warframe Augment Mods listed as non tradable
A lot of the warframe augment mods (https://warframe.fandom.com/wiki/Warframe_Augment_Mods), if not all (I didn't test everything), are listed as `tradable: false` even though they are tradable.

Examples:

- Guided Effigy
- Mesa's Waltz
- Seeking Shuriken
- Fracturing Crush
- Vampire Leech

### PR DESCRIPTION
**Pull request by Nakroma**
resolves #107

### CODE REVIEW

**Comment by TobiTenno** [comment]
looking at some of the item data, i think this route won't be perfect, because it looks like it also includes things like [Ambush](https://warframe.fandom.com/wiki/Ambush) (ID: `/Lotus/Types/Sentinels/SentinelPrecepts/GhostAugmentCard`), which is just a normal precept.

**Comment by TobiTenno** [comment]
I don't know that anything else will be perfect, cause this definitely looks like the most sure way

**Comment by TobiTenno** [comment]
Potentially might want to make it "Augment Card" just to be in line with the others?

**Comment by TobiTenno** [comment]
I also wonder if it'd be better to add an `isAugment` boolean on the object and check that for the tradeable check, then we could just override the value for ambush to be `false` for `isAugment`

**Comment by Nakroma** [comment]
Ambush is still tradable tho, so it would correctly catch at least that, at least for now it's just a wrong type (which it is anyway currently, it would just change it)

**Comment by TobiTenno** [comment]
very true...
I just don't know that de-typing them as warframe mods will make this an overall good fix.... sorry, just trying to think through and think if i could've written out my initial notes better.

**Comment by TobiTenno** [comment]
hmmmm.... what would you think of doing it the boolean on the object way, and adding better types for sentinel mods so that it also gets marked as tradeable properly?

**Comment by Nakroma** [comment]
sounds like a good idea

**Comment by TobiTenno** [comment]
(@Nakroma hey, sorry for the pingalicious ping... you still down to do that part? I might pick up the branch otherwise and work on it a bit if you're too busy)

**Comment by Nakroma** [comment]
I'm currently back in uni + some other things, so I don't sadly. Feel free to pick it up, if you have the time :)

**Comment by TobiTenno** [comment]
will do. ty for contributing all that you did, it's a giant help.

**Pull request closed without merging**
