### PR TITLE
Added Typescript type declaration file

### PR DESCRIPTION
**Pull request by Drakmyth**
Built this file for use in my own app and after seeing #58 not resulting in an official file I figured I'd push this back up. From within a Typescript app, the library can be used like so:
```
import Items from 'warframe-items';

const items = new Items({ category: ['All'] });
```
or if you need other types
```
import Items, { ItemsOptions } from 'warframe-items';

const options: ItemsOptions = { category: ['All'] };
const items = new Items(options);
```

I tested the validity of this by installing [typescript-json-schema](https://github.com/YousefED/typescript-json-schema) and [ajv](https://github.com/epoberezkin/ajv) and running
```
typescript-json-schema ./index.d.ts Items --out items.schema.json --noExtraProps --required --strictNullChecks
```
to generate a json-schema and then
```
ajv validate -s ./items.schema.json -d ./data/json/All.json --all-errors --verbose
```
to validate All.json against it, and tweaking the types until no more errors were reported. This is probably a good candidate for an automated test, but I'm not familiar enough with mocha to write this myself just now.

Of note are the string unions making up the bottom half of the file. I created these manually but it should be fairly easy to automate the generation of these so that as new values are added these types remain accurate.

I am a little concerned by some of the data having inconsistent types (for example, "vaulted" can be a `true`/`false` boolean or the string `"N/A"`) but I'm not sure if the scraper has any kind of ETL process to normalize the data or not and didn't want to start touching that if it doesn't.

Finally I should note that while this works for how the library exists today, it would be somewhat nicer if interfaces for each type of item could be split out and the main `Item` type be defined as a union of those interfaces. I started to go down that road, but there is so much data and with all the optional fields and such I suspect a generation process for this file would need to be in place before that is feasible, and this is a good first step.

If there are any clarifications I can provide or questions I can answer, please ask! Happy to contribute to such a great project!

### CODE REVIEW

**Comment by Drakmyth** [comment]
Unrelated, I believe the ci failure prior to my marking this PR as ready for review is due to the ci process not supporting [Draft Pull Requests](https://github.blog/2019-02-14-introducing-draft-pull-requests/). Just wanted to call that out.

**Comment by TobiTenno** [comment]
That's largely the reason it doesn't pick up on CI for the draft, but that's kind of intended, that way it doesn't run a ton extra processes when ultimately drafts are like "not for our eyes" yet.

**Comment by TobiTenno** [comment]
Also, dunno if this changed, but the last time i went about building out the defs for a project, it was SOP to add it to the package.json "types", could you add that for me?

**Comment by Drakmyth** [comment]
> Also, dunno if this changed, but the last time i went about building out the defs for a project, it was SOP to add it to the package.json "types", could you add that for me?

Looks like if the main script is index.js and the type declaration is index.d.ts then adding "types" to package.json is not required, but is still recommended. I'll make that change this evening and get it pushed up.

**Comment by TobiTenno** [comment]
> I'll make that change this evening and get it pushed up.

Sounds good, while it's probably unnecessary for most, it will definitely help. I should probably look at copying a lot of this over to wfcd/api-spec for those applicable bits, too

**Pull request merged**
