### PR TITLE
fix: force resources to be Resource-type

### LINKED ISSUE #427: [Bug] Missing item types
### Describe the bug

Resources do not have a type: resource.

### NodeJS Version

n/a

### npm Version

n/a

### warframe-items Version

n/a

### Access Method

warframestat.us API

### What happened?

All the broken types I could spot (that were either typed with something weird or had "Misc")
- Nano Spores
- Alloy Plate
- Salvage
- Rubedo
- Plastids
- Circuits
- Orokin Cell
- Argon Crystal
- Control Module
- Mutalist Alad V Nav Coordinate
- Cryptographic ALU
- Omega Isotope
- Riven Sliver
- Kuva
- Steel Essence
- ~~Isos (completely broke? not Misc/Resource)~~ (2 items same name)
- Morphics
- Cryotic
- Hexenon
- Neural Sensors
- Oxium
- Polymer Bundle
- Tellurium
- Spectral Debris
- Aya
- Somatic Fibers
- Endo
- Nav Coordinate
- Judgement Points
- Synthula
- Javlok Capacitor
- Vitus Essence
- Void Traces
- Gallium
- Antiserum Injector Fragment

### PR DESCRIPTION
**Pull request by TobiTenno**
### What did you fix? 
closes #427 

---

### Reproduction steps
add overrides for affected resources

---

### Considerations
- Does this contain a new dependency? **[No]**
- Does this introduce opinionated data formatting or manual data entry? **[Yes]**
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[No]**
- Have I run the linter? **[Yes]**
- Is is a bug fix, feature request, or enhancement? **[Bug Fix]**

### CODE REVIEW

**Comment by AyAyEm** [comment]
A few types and categories have gone wrong but overall it's all good.

```js
{
   category: 'Misc', // should be Resource
   type: 'Resource',
   uniqueName: '/Lotus/Types/Items/MiscItems/Rubedo'
}
```

```js
{
    category: 'Misc',
    name: 'Amp Arcane Adapter', // it's the same for Exlius, Secondary and Primary
    type: 'Rifle', // Should be resource or some type of forma but definitely not a weapon
    uniqueName: '/Lotus/Types/Items/MiscItems/WeaponAmpArcaneUnlocker'
}
```

**Comment by TobiTenno** [comment]
@AyAyEm just waiting for your eyes, if you've got time

**Review by AyAyEm — APPROVED** [review]
Great work, it's much more useful the category and type combination for many items now.

**Pull request merged**
