### PR TITLE
fix: typo causing test failure

### PR DESCRIPTION
**Pull request by Sainan**

### CODE REVIEW

**Comment by Sainan** [comment]
Umm, why did you close this?

**Comment by SlayerOrnstein** [comment]
I think gh just auto closes when it does a force push...

**Comment by SlayerOrnstein** [comment]
This should work

**Comment by Sainan** [comment]
Well, all that needs to be done is to write 'Vazarin' instead of 'Varazin'.

**Comment by SlayerOrnstein** [comment]
yeah yeah just push an empty commit on the same branch and it should let you reopen

**Pull request closed without merging**
