### PR TITLE
Patch badge for current update

### PR DESCRIPTION
**Pull request by TobiTenno**
add automated badge update to show the latest update this has built with

(yes, i typo'd the branch name)

### CODE REVIEW

**Comment by TobiTenno** [comment]
the badge doesn't look right on that branch.

should i just remove the logo?

**Comment by Kaptard** [comment]
Yeah, the badge doesn't even load for me because of a 414 response (url too long). Do we have to provide the entire image data or do they also accept links?

**Comment by TobiTenno** [comment]
I think it has to be the base64'd data. i'll see if i can find a way to shorten it

**Comment by TobiTenno** [comment]
works, it's just a bad aspect ratio now

**Comment by Kaptard** [comment]
Are you sure we wanna remove the WFCD banner? I doubt people will notice that badge as much as the banner, and I feel like guiding other devs to the organization has rather high priority.

About the order of badges, maybe it makes sense to put the update badge in front or behind the npm badge, as it's certainly more important for the end user than the build state or dependencies.

**Comment by TobiTenno** [comment]
I'm fine with whichever order

**Comment by Kaptard** [comment]
What about the WFCD banner though? Was there any particular reason to use the badge instead?

**Comment by TobiTenno** [comment]
If you think the banner makes it more effective, let's go with that.

**Pull request merged**
